[package]
name = "ykrt"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
yktrace = { path = "../yktrace" }
ykcompile = { path = "../ykcompile" }
