[package]
name = "ykrt"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
hwtracer = { path = "../hwtracer" }
libc = "0.2.117"
num_cpus = "1.13.1"
parking_lot = "0.12.0"
parking_lot_core = "0.9.1"
tempfile = "3.3.0"
ykfr = { path = "../ykfr" }
yksmp = { path = "../yksmp" }
yktracec = { path = "../yktracec" }
ykutil = { path = "../ykutil" }

[build-dependencies]
regex = "1.5.4"
ykbuild = { path = "../ykbuild" }

[features]
yk_jitstate_debug = []
yk_testing = []
