[package]
name = "ykrt"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
num_cpus = "1.13.0"
once_cell = "1.8.0"
parking_lot = "0.11.1"
parking_lot_core = "0.8.3"
strum = { version = "0.21.0", features = ["derive"] }
yktrace = { path = "../yktrace" }

[build-dependencies]
regex = "1.5.4"

[features]
jit_state_debug = []
