[package]
name = "ykcapi"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.117"
ykllvmwrap = { path = "../ykllvmwrap" }
ykrt = { path = "../ykrt" }
yktrace = { path = "../yktrace" }
yksmp = { path = "../yksmp" }

[features]
yk_testing = []
jit_state_debug = []
