[workspace]
members = [
    "hwtracer",
    "tests",
    "ykaddr",
    "ykbuild",
    "ykcapi",
    "ykrt",
    "yksmp",
    "xtask",
]
resolver = "2"

[profile.release-with-debug]
inherits = "release"
debug = true

[patch.crates-io]
fm = { git = "https://github.com/softdevteam/fm/" }
