[package]
name = "hwtracer"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.71"
lazy_static = "1.4.0"
time = "0.2.16"
tempfile = "3.1.0"

[build-dependencies]
cc = "1.0.57"
