[package]
name = "ykpack"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
bincode = "1.3.1"
bitflags = "1.2.1"
fallible-iterator = "0.2.0"
fxhash = "0.2.1"
serde = { version = "1.0.118", features = ["derive"] }
