[package]
name = "ykpack"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
fallible-iterator = "0.2.0"
bincode = "1.3.1"
