[package]
name = "ykpack"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
fallible-iterator = "0.2"
rmp-serde = "=0.14.0"
