# The service providing the commit statuses to GitHub.

status = ["buildbot/yk-buildbot-build-script-hw"]

# Allow 10 minutes for builds.
timeout_sec = 600

# Have bors delete auto-merged branches.
# Doesn't work on forks, but still.
delete_merged_branches = true

# Don't include the PR description in the merge commit.
cut_body_after = ""
