[package]
name = "hwtracer"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = "0.2.80"
lazy_static = "1.4.0"
tempfile = "3.1.0"
phdrs = { git = "https://github.com/softdevteam/phdrs" }
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
strum_macros = "0.24.3"
deku = "0.14.1"

[build-dependencies]
cc = "1.0.62"
rerun_except = "0.1.2"
