[package]
name = "yktrace"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
byteorder = "1.4.3"
elf = "0.0.10"
fxhash = "0.2.1"
gimli = "0.26.1"
hwtracer = { git = "https://github.com/ykjit/hwtracer" }
intervaltree = "0.2.7"
leb128 = "0.2.5"
libc = "0.2.117"
memmap2 = "0.5.2"
phdrs = { git = "https://github.com/softdevteam/phdrs" }
ykllvmwrap = { path = "../ykllvmwrap" }
ykutil = { path = "../ykutil" }

[dependencies.object]
version = "0.28.3"
default-features = false
features = ["read_core", "elf"]

[dev-dependencies]
fm = "0.2.1"
regex = "1.5.4"

[features]
yk_testing = []
