[package]
name = "yktrace"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
gimli = "0.23.0"
hwtracer = { git = "https://github.com/softdevteam/hwtracer" }
libc = "0.2.82"
phdrs = { git = "https://github.com/softdevteam/phdrs" }

[dependencies.object]
version = "0.23.0"
default-features = false
features = ["read_core", "elf"]

[dev-dependencies]
fm = "0.2.0"
regex = "1.4.3"
