[package]
name = "ykview"
version = "0.1.0"
authors = ["bjorn3 <bjorn3@users.noreply.github.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
ykpack = { path = "../ykpack" }
yktrace = { path = "../yktrace" }
