[package]
name = "ykutil"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = "0.2.82"
memmap2 = "0.2.2"
object = "0.24.0"
once_cell = "1.7.2"
phdrs = { git = "https://github.com/softdevteam/phdrs" }
