[package]
name = "ykutil"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = "0.2.97"
memmap2 = "0.3.0"
object = "0.25.3"
once_cell = "1.8.0"
phdrs = { git = "https://github.com/softdevteam/phdrs" }
