[package]
name = "ykview"
version = "0.1.0"
authors = ["The Yorick Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
memmap2 = "0.2.0"
ykpack = { path = "../ykpack" }
yktrace = { path = "../yktrace" }
