# cargo will walk up the filesystem and find the external workspace's config
# which disables optimisation. We don't want that for the internal workspace,
# so we force the opt-levels back to their default values.

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3
